In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
%matplotlib inline

In [2]:
pd.__version__

'1.1.3'

In [9]:
A = np.array([1,2,3],[4,5,6],[7,8,9])

NameError: name 'np' is not defined

In [10]:
import numpy as np

In [11]:
A = np.array([1,2,3],[4,5,6],[7,8,9])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [12]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
arrray([[1, 2, 3]),
        [4, 5, 6],
        [7, 8, 9]])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (<ipython-input-13-503604de480d>, line 1)

In [14]:
arrray([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

NameError: name 'arrray' is not defined

In [15]:
import numpy as np

In [16]:
arrray([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

NameError: name 'arrray' is not defined

In [17]:
import numpy as np
arrray([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

NameError: name 'arrray' is not defined

In [18]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [19]:
 A[0]

array([1, 2, 3])

In [20]:
A[1]

array([4, 5, 6])

In [21]:
A[2]

array([7, 8, 9])

In [22]:
A[:,0]

array([1, 4, 7])

In [24]:
A[:,1]

array([2, 5, 8])

In [25]:
A[2,:]

array([7, 8, 9])

In [27]:
A[1,0]

4

In [28]:
A.shape

(3, 3)

In [30]:
np.shape(A)

(3, 3)

In [33]:
A[1:2,:2]

array([[4, 5]])

In [34]:
A[1:3,:3]

array([[4, 5, 6],
       [7, 8, 9]])